print "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
print "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
print "XX                                                                          XX"
print "XX   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM   XX"
print "XX   MMMMMMMMMMMMMMMMMMMMMssssssssssssssssssssssssssMMMMMMMMMMMMMMMMMMMMM   XX"
print "XX   MMMMMMMMMMMMMMMMss'''                          '''ssMMMMMMMMMMMMMMMM   XX"
print "XX   MMMMMMMMMMMMyy''                                    ''yyMMMMMMMMMMMM   XX"
print "XX   MMMMMMMMyy''                                            ''yyMMMMMMMM   XX"
print "XX   MMMMMy''                                                    ''yMMMMM   XX"
print "XX   MMMy'                                                          'yMMM   XX"
print "XX   Mh'                                                              'hM   XX"
print "XX   -                                                                  -   XX"
print "XX                                                                          XX"
print "XX   ::                                                                ::   XX"
print "XX   MMhh.        ..hhhhhh..                      ..hhhhhh..        .hhMM   XX"
print "XX   MMMMMh   ..hhMMMMMMMMMMhh.                .hhMMMMMMMMMMhh..   hMMMMM   XX"
print "XX   ---MMM .hMMMMdd:::dMMMMMMMhh..        ..hhMMMMMMMd:::ddMMMMh. MMM---   XX"
print "XX   MMMMMM MMmm''      'mmMMMMMMMMyy.  .yyMMMMMMMMmm'      ''mmMM MMMMMM   XX"
print "XX   ---mMM ''             'mmMMMMMMMM  MMMMMMMMmm'             '' MMm---   XX"
print "XX   yyyym'    .              'mMMMMm'  'mMMMMm'              .    'myyyy   XX"
print "XX   mm''    .y'     ..yyyyy..  ''''      ''''  ..yyyyy..     'y.    ''mm   XX"
print "XX           MN    .sMMMMMMMMMss.   .    .   .ssMMMMMMMMMs.    NM           XX"
print "XX           N\`    MMMMMMMMMMMMMN   M    M   NMMMMMMMMMMMMM    \`N           XX"
print "XX            +  .sMNNNNNMMMMMN+   \`N    N\`   +NMMMMMNNNNNMs.  +            XX"
print "XX              o+++     ++++Mo    M      M    oM++++     +++o              XX"
print "XX                                oo      oo                                XX"
print "XX           oM                 oo          oo                 Mo           XX"
print "XX         oMMo                M              M                oMMo         XX"
print "XX       +MMMM                 s              s                 MMMM+       XX"
print "XX      +MMMMM+            +++NNNN+        +NNNN+++            +MMMMM+      XX"
print "XX     +MMMMMMM+       ++NNMMMMMMMMN+    +NMMMMMMMMNN++       +MMMMMMM+     XX"
print "XX     MMMMMMMMMNN+++NNMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMNN+++NNMMMMMMMMM     XX"
print "XX     yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy     XX"
print "XX   m  yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy  m   XX"
print "XX   MMm yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy mMM   XX"
print "XX   MMMm .yyMMMMMMMMMMMMMMMM     MMMMMMMMMM     MMMMMMMMMMMMMMMMyy. mMMM   XX"
print "XX   MMMMd   ''''hhhhh       odddo          obbbo        hhhh''''   dMMMM   XX"
print "XX   MMMMMd             'hMMMMMMMMMMddddddMMMMMMMMMMh'             dMMMMM   XX"
print "XX   MMMMMMd              'hMMMMMMMMMMMMMMMMMMMMMMh'              dMMMMMM   XX"
print "XX   MMMMMMM-               ''ddMMMMMMMMMMMMMMdd''               -MMMMMMM   XX"
print "XX   MMMMMMMM                   '::dddddddd::'                   MMMMMMMM   XX"
print "XX   MMMMMMMM-                                                  -MMMMMMMM   XX"
print "XX   MMMMMMMMM                                                  MMMMMMMMM   XX"
print "XX   MMMMMMMMMy                                                yMMMMMMMMM   XX"
print "XX   MMMMMMMMMMy.                                            .yMMMMMMMMMM   XX"
print "XX   MMMMMMMMMMMMy.                                        .yMMMMMMMMMMMM   XX"
print "XX   MMMMMMMMMMMMMMy.                                    .yMMMMMMMMMMMMMM   XX"
print "XX   MMMMMMMMMMMMMMMMs.                                .sMMMMMMMMMMMMMMMM   XX"
print "XX   MMMMMMMMMMMMMMMMMMss.           ....           .ssMMMMMMMMMMMMMMMMMM   XX"
print "XX   MMMMMMMMMMMMMMMMMMMMNo         oNNNNo         oNMMMMMMMMMMMMMMMMMMMM   XX"
print "XX                                                                          XX"
print "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
print "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
print "    .o88o.                               o8o                ."
print "    888 \`\"                               \`\"'              .o8"
print "   o888oo   .oooo.o  .ooooo.   .ooooo.  oooo   .ooooo.  .o888oo oooo    ooo"
print "    888    d88(  \"8 d88' \`88b d88' \`\"Y8 \`888  d88\' \`88b   888    \`88.  .8\'"
print "    888    \`\"Y88b.  888   888 888        888  888ooo888   888     \`88..8'"
print "    888    o.  )88b 888   888 888   .o8  888  888    .o   888 .    \`888\'"
print "   o888o   8\"\"888P' \`Y8bod8P' \`Y8bod8P' o888o \`Y8bod8P'   \"888\"      d8\'"
print "                                                                .o...P\'"
print "                                                                \`XER0\'"

